### ISSUE TITLE
result of getBytes to bytes array

### ISSUE THREAD

**Issue by DogeWatch** [justfoxing/jfx_bridge#9] opened 2020-05-27 06:07 UTC
if I use `bytes(getBytes(xxx))`, there will be an error:
File "xxx/bridge.py", line 1114, in __get__
raise AttributeError()

**Comment by justfoxing** [comment] 2020-05-29 00:54
Ref the bytes_new function at https://github.com/python/cpython/blob/a81849b0315277bb3937271174aaaa5059c0b445/Objects/bytesobject.c#L2542

When bytes() is called, there's a _PyIndex_Check call at L2617 to see if __index__ is defined for this type, and if it is, it proceeds into PyNumber_AsSsize_t which calls __index__, thus triggering the failure. What we actually want to happen is for the _PyIndex_Check to return false, and the code to fall through to the final case PyBytes_FromObject.

__index__ is defined on BridgedObject by my code for automatically registering all operator methods as class methods, so that's the root cause of this bug - __index__ is being defined, but just straight up doesn't exist.

Best solution is probably dusting off the feature-dynamic-types branch and completing that work, so that the BridgedObjects will have the correct class methods for their remote type. I'll move that up my TODO list.

**Comment by justfoxing** [comment] 2020-06-01 01:46
Fixed in version 0.3.0 of jfx_bridge (no version bump for ghidra_bridge).

Upgrade with `pip install ghidra_bridge --upgrade --force-reinstall` to get the latest jfx_bridge component, then re-install the server scripts with `python -m ghidra_bridge.install_server <script location>`.

Then your original `bytes(getBytes(xxx))` should work as expected.

**Closed by justfoxing** 2020-06-01 01:46 UTC
Labels: bug, reproduced
